name: 'Generate .luacheckrc'

description: 'Generate .luacheckrc for FantasyGrounds extensions'

inputs:
  target-path:
    description: 'Path to .luacheckrc'
    required: true
    default: '.luacheckrc'
  header-path:
    description: 'Path to .luacheckrc header template'
    required: false
    default: '.luacheckrc_header'
  token:
    description: 'GitHub PAT'
    required: false

runs:
  using: "composite"
  steps:
    - name: Clone FG-Unofficial-Developers-Guild/CoreRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/CoreRPG
        path: .fg/rulesets/CoreRPG
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/2E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/2E
        path: .fg/rulesets/2E
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/3.5E
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/3.5E
        path: .fg/rulesets/35E
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/4e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/4e
        path: .fg/rulesets/4E
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/5e
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/5e
        path: .fg/rulesets/5E
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG
        path: .fg/rulesets/PFRPG
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/PFRPG2
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/PFRPG2
        path: .fg/rulesets/PFRPG2
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Clone FG-Unofficial-Developers-Guild/SFRPG
      uses: actions/checkout@v3
      with:
        repository: FG-Unofficial-Developers-Guild/SFRPG
        path: .fg/rulesets/SFRPG
        fetch-depth: 0
        token: '${{ inputs.token }}'

    - name: Install Lua 5.1
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1"

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install LuaFileSystem
      run: luarocks install luafilesystem
      shell: bash

    - name: Create globals folder
      run: mkdir $GITHUB_ACTION_PATH/.fg/globals
      shell: bash

    - name: Parse globals
      run: lua $GITHUB_ACTION_PATH/parse_global.lua
      shell: bash

    - name: Generate .luacheckrc
      run: lua $GITHUB_ACTION_PATH/generate.lua ${{ inputs.target-path }} ${{ inputs.header-path }}
      shell: bash

    - name: Clean up
      run: rm -rf .install .lua .luarocks .fg
      shell: bash
