name: 'Generate .luacheckrc'

description: 'Generate .luacheckrc for FantasyGrounds extensions'

inputs:
  target-path:
    description: 'Path to .luacheckrc'
    required: true
    default: '.luacheckrc'
  header-path:
    description: 'Path to .luacheckrc header template'
    required: false
    default: '.luacheckrc_header'
  std:
    description: 'String of std definitions to use'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Lua 5.1
      uses: leafo/gh-actions-lua@v9
      with:
        luaVersion: "5.1"

    - name: Install Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install LuaFileSystem
      run: luarocks install luafilesystem
      shell: bash

    - name: Install lua-xmlparser
      run: luarocks install xmlparser
      shell: bash

    - name: Parse globals
      run: lua $GITHUB_ACTION_PATH/parse_global.lua $GITHUB_ACTION_PATH/fg_apis.lua
      shell: bash

    - name: Generate .luacheckrc
      run: lua $GITHUB_ACTION_PATH/generate.lua ${{ inputs.std }} ${{ inputs.header-path }} ${{ inputs.target-path }}
      shell: bash

    - name: Clean up
      run: rm -rf .install .lua .luarocks .fg
      shell: bash
